version: "2"
run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - errcheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
linters-settings:
  errcheck:
    # Be pragmatic: don't require checking of Close for defer patterns in tests/examples.
    # (Keep defaults; exclusions above handle test files.)
